-- CreateTable
CREATE TABLE "McProject" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "boards" TEXT[],
    "state" JSONB,
    "reconcileMode" TEXT NOT NULL DEFAULT 'preview',
    "lastReconciledAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "McProject_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "McTaskState" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "board" TEXT NOT NULL,
    "kanbanId" TEXT NOT NULL,
    "idempotencyKey" TEXT,
    "title" TEXT NOT NULL,
    "kanbanStatus" TEXT NOT NULL,
    "normalizedStatus" TEXT NOT NULL,
    "classification" TEXT NOT NULL,
    "kanbanStale" BOOLEAN NOT NULL DEFAULT false,
    "evidence" JSONB NOT NULL,
    "reasons" JSONB NOT NULL,
    "recommendedResolution" TEXT,
    "reconciliationVersion" TEXT NOT NULL,
    "reconciledAt" TIMESTAMP(3) NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "McTaskState_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "McReceipt" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'execution',
    "paths" TEXT[],
    "result" TEXT NOT NULL,
    "rawResult" TEXT,
    "qcVerdict" TEXT,
    "finishedAt" TIMESTAMP(3),
    "actionRequired" BOOLEAN NOT NULL DEFAULT false,
    "integrity" TEXT NOT NULL,
    "identity" JSONB,
    "firstSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "McReceipt_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "McReconciliation" (
    "id" TEXT NOT NULL,
    "intentId" TEXT NOT NULL,
    "mode" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "taskId" TEXT,
    "board" TEXT,
    "outcome" TEXT NOT NULL,
    "oldStatus" TEXT,
    "newStatus" TEXT,
    "reason" TEXT NOT NULL,
    "authoritativeEvidenceId" TEXT,
    "detail" JSONB,
    "reconciliationVersion" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "McReconciliation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "McApproval" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "requestedAction" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "packageId" TEXT,
    "packageSha256" TEXT,
    "packageMatches" BOOLEAN,
    "approver" TEXT,
    "decidedAt" TIMESTAMP(3),
    "executionBoundary" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "McApproval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "McEvent" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "projectId" TEXT,
    "subjectId" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL,
    "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "McEvent_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "McTaskState_projectId_classification_idx" ON "McTaskState"("projectId", "classification");

-- CreateIndex
CREATE INDEX "McTaskState_projectId_normalizedStatus_idx" ON "McTaskState"("projectId", "normalizedStatus");

-- CreateIndex
CREATE UNIQUE INDEX "McTaskState_board_kanbanId_key" ON "McTaskState"("board", "kanbanId");

-- CreateIndex
CREATE INDEX "McReceipt_projectId_idx" ON "McReceipt"("projectId");

-- CreateIndex
CREATE INDEX "McReconciliation_projectId_createdAt_idx" ON "McReconciliation"("projectId", "createdAt");

-- CreateIndex
CREATE INDEX "McReconciliation_taskId_idx" ON "McReconciliation"("taskId");

-- CreateIndex
CREATE UNIQUE INDEX "McReconciliation_intentId_mode_key" ON "McReconciliation"("intentId", "mode");

-- CreateIndex
CREATE INDEX "McApproval_projectId_status_idx" ON "McApproval"("projectId", "status");

-- CreateIndex
CREATE INDEX "McEvent_projectId_occurredAt_idx" ON "McEvent"("projectId", "occurredAt");

-- CreateIndex
CREATE INDEX "McEvent_type_idx" ON "McEvent"("type");


-- ─── Hardening (hand-written; not generated by Prisma) ─────────────
-- Supabase default privileges grant anon/authenticated full access to new
-- public tables. These tables are server-to-server only: revoke that, then
-- grant least privilege to the two application roles when they exist (they
-- do not exist in CI or local databases, so every step is guarded).

DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['McProject','McTaskState','McReceipt','McReconciliation','McApproval','McEvent'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
      EXECUTE format('REVOKE ALL ON TABLE %I FROM anon', t);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
      EXECUTE format('REVOKE ALL ON TABLE %I FROM authenticated', t);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'hermes_web') THEN
      EXECUTE format('GRANT SELECT ON TABLE %I TO hermes_web', t);
    END IF;
  END LOOP;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'hermes_bridge') THEN
    -- Current state the bridge recomputes each cycle: no DELETE.
    GRANT SELECT, INSERT, UPDATE ON TABLE "McProject", "McTaskState", "McReceipt", "McApproval" TO hermes_bridge;
    -- Audit ledger and event log: append-only.
    GRANT SELECT, INSERT ON TABLE "McReconciliation", "McEvent" TO hermes_bridge;
  END IF;
END
$$;

-- Append-only enforcement for the audit ledger and event log, independent of
-- grants (also binds the table owner). Rollback drops it with the tables.
CREATE OR REPLACE FUNCTION "mc_append_only"() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = 'insufficient_privilege';
END
$$;

CREATE TRIGGER "McReconciliation_append_only"
  BEFORE UPDATE OR DELETE ON "McReconciliation"
  FOR EACH ROW EXECUTE FUNCTION "mc_append_only"();

CREATE TRIGGER "McEvent_append_only"
  BEFORE UPDATE OR DELETE ON "McEvent"
  FOR EACH ROW EXECUTE FUNCTION "mc_append_only"();
